# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: messages.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'messages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\x12\x08messages\" \n\rClientMessage\x12\x0f\n\x07request\x18\x01 \x01(\t\"\"\n\x0e\x43lientResponse\x12\x10\n\x08response\x18\x01 \x01(\t\"0\n\rDeviceMessage\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\"5\n\x0e\x44\x65viceResponse\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x10\n\x08response\x18\x02 \x01(\t\"<\n\x0f\x44iscoverMessage\x12\x0f\n\x07request\x18\x01 \x01(\t\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\"M\n\x10\x44iscoverResponse\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\x12\x0c\n\x04type\x18\x04 \x01(\x05\x42&Z$github.com/username/gateway/messagesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z$github.com/username/gateway/messages'
  _globals['_CLIENTMESSAGE']._serialized_start=28
  _globals['_CLIENTMESSAGE']._serialized_end=60
  _globals['_CLIENTRESPONSE']._serialized_start=62
  _globals['_CLIENTRESPONSE']._serialized_end=96
  _globals['_DEVICEMESSAGE']._serialized_start=98
  _globals['_DEVICEMESSAGE']._serialized_end=146
  _globals['_DEVICERESPONSE']._serialized_start=148
  _globals['_DEVICERESPONSE']._serialized_end=201
  _globals['_DISCOVERMESSAGE']._serialized_start=203
  _globals['_DISCOVERMESSAGE']._serialized_end=263
  _globals['_DISCOVERRESPONSE']._serialized_start=265
  _globals['_DISCOVERRESPONSE']._serialized_end=342
# @@protoc_insertion_point(module_scope)
