# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: messages.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'messages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\x12\x08messages\" \n\rClientMessage\x12\x0f\n\x07request\x18\x01 \x01(\t\"#\n\x0f\x43lienteResponse\x12\x10\n\x08response\x18\x01 \x01(\t\"0\n\rDeviceMessage\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\"5\n\x0e\x44\x65viceResponse\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x10\n\x08response\x18\x02 \x01(\t\"\"\n\x0f\x44iscoverMessage\x12\x0f\n\x07request\x18\x01 \x01(\t\"|\n\x10\x44iscoverResponse\x12\x31\n\x06\x64\x65vice\x18\x01 \x03(\x0b\x32!.messages.DiscoverResponse.Device\x1a\x35\n\x06\x44\x65vice\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLIENTMESSAGE']._serialized_start=28
  _globals['_CLIENTMESSAGE']._serialized_end=60
  _globals['_CLIENTERESPONSE']._serialized_start=62
  _globals['_CLIENTERESPONSE']._serialized_end=97
  _globals['_DEVICEMESSAGE']._serialized_start=99
  _globals['_DEVICEMESSAGE']._serialized_end=147
  _globals['_DEVICERESPONSE']._serialized_start=149
  _globals['_DEVICERESPONSE']._serialized_end=202
  _globals['_DISCOVERMESSAGE']._serialized_start=204
  _globals['_DISCOVERMESSAGE']._serialized_end=238
  _globals['_DISCOVERRESPONSE']._serialized_start=240
  _globals['_DISCOVERRESPONSE']._serialized_end=364
  _globals['_DISCOVERRESPONSE_DEVICE']._serialized_start=311
  _globals['_DISCOVERRESPONSE_DEVICE']._serialized_end=364
# @@protoc_insertion_point(module_scope)
